name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          # If your Dockerfile isn't in the root directory, specify the path
          # context: ./path/to/Dockerfile/directory